name: selfprivacy
description: selfprivacy.org
publish_to: 'none'
version: 0.13.3+32

environment:
  sdk: '>=3.7.0 <4.0.0'
  # RECOMMENDED_FLUTTER_VERSION=3.32.6
  flutter: ">=3.32.0 <3.33.0"

dependencies:
  animations: ^2.0.11
  auto_route: ^10.1.0+1
  auto_size_text: ^3.0.0
  bloc_concurrency: ^0.3.0
  collection: ^1.18.0
  crypt: ^4.3.1
  cubit_form: ^2.0.5
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  duration: ^4.0.3
  # When updated, check if they now support new color roles and remove the
  # workaround from the theme factory.
  dynamic_color: ^1.7.0
  easy_localization: ^3.0.6
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  # Discontinued! Needs to be replaced
  # https://github.com/flutter/flutter/issues/162966
  flutter_markdown: ^0.7.7+1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  get_it: ^8.0.3
  gql: ^1.0.0+1
  graphql: ^5.2.1
  graphql_flutter: ^5.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  http: ^1.4.0
  intl: ^0.20.2
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  material_color_utilities: ^0.11.1
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^8.3.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5
  pub_semver: ^2.2.0
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  skeletonizer: ^2.1.0
  timezone: ^0.10.1
  url_launcher: ^6.3.2
#  wakelock: ^0.6.2 # TODO: Developer is not available, update later.

dependency_overrides:
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  cupertino_icons: ^1.0.8
  custom_lint: ^0.7.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  graphql_codegen: ^1.2.4
  hive_ce_generator: ^1.9.2
  json_serializable: ^6.9.5
  sp_lints:
    git: https://git.selfprivacy.org/SelfPrivacy/sp-lints.git

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/icon/logo_android.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/icon/logo_android_adaptive_fg.png"
  adaptive_icon_background: "#ffffff"
  image_path_ios: "assets/images/icon/logo_ios.png"
  image_path: "assets/images/icon/logo_ios.png"
  adaptive_icon_monochrome: "assets/images/icon/selfprivacy_dynamic.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/logos/
    - assets/images/gifs/
    - assets/translations/
    - assets/markdown/
  fonts:
    - family: BrandIcons
      fonts:
        - asset: assets/fonts/BrandIcons.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
